version: '3'
services:
  memberlist:
    build: .
    # security_opt:
    #   - seccomp:unconfined
    # entrypoint: dlv debug . -l 0.0.0.0:2345 --headless=true --log=true -- server
    # volumes:
    #   - .:/memberlist
    # ports:
    #   - "2345:2345"
    # expose:
    #   - "2345"

